def seed_v3(seeder):
    print(">> Running V3 seed...")
    list(seeder.seed_countries())
    list(seeder.seed_regions())
    list(seeder.seed_cities())
    list(seeder.seed_weather_stations())
    list(seeder.seed_sensors())
    list(seeder.seed_weather_measurements())
    seeder.seed_health_risk_levels()
    list(seeder.seed_monthly_weather_statistics())
    list(seeder.seed_users())
    seeder.seed_user_home_locations()
    seeder.seed_user_units_settings()
    seeder.seed_user_pollen_preferences()
    seeder.seed_user_favorite_locations()
    seeder.seed_user_history_recent_views()
