def seed_v5(seeder):
    print(">> Running V5 seed...")
    list(seeder.seed_countries())
    list(seeder.seed_regions())
    list(seeder.seed_cities())
    list(seeder.seed_weather_stations())
    list(seeder.seed_sensors())
    list(seeder.seed_weather_measurements())
    seeder.seed_health_risk_levels()
    list(seeder.seed_monthly_weather_statistics())
    list(seeder.seed_users())
    seeder.seed_user_home_locations()
    seeder.seed_user_units_settings()
    seeder.seed_user_pollen_preferences()
    seeder.seed_user_favorite_locations()
    seeder.seed_user_history_recent_views()
    list(seeder.seed_notifications())
    seeder.seed_user_notification_preferences()
    list(seeder.seed_external_data_sources())
    seeder.seed_external_weather_data()
