FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends postgresql-client && \
    rm -rf /var/lib/apt/lists/*

RUN pip install psycopg2-binary

RUN pip install python-dotenv

COPY migration_tester.py /migration_tester.py

WORKDIR /

CMD ["python", "/migration_tester.py"]