DROP TABLE IF EXISTS PollenMeasurement CASCADE;
DROP TABLE IF EXISTS WeatherMeasurement CASCADE;
DROP TABLE IF EXISTS Sensor CASCADE;
DROP TABLE IF EXISTS WeatherStation CASCADE;
DROP TABLE IF EXISTS MonthlyWeatherStatistics CASCADE;
DROP TABLE IF EXISTS HealthRiskLevel CASCADE;