DROP TABLE IF EXISTS UserHistoryRecentViews CASCADE;
DROP TABLE IF EXISTS UserFavoriteLocations CASCADE;
DROP TABLE IF EXISTS UserPollenPreferences CASCADE;
DROP TABLE IF EXISTS UserUnitsSettings CASCADE;
DROP TABLE IF EXISTS UserHomeLocation CASCADE;
DROP TABLE IF EXISTS Users CASCADE;